# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wishes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Wishes

  pod 'GoogleSignIn'
  pod 'GTMAppAuth'

  target 'WishesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Wishes-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Wishes-tvOS

  target 'Wishes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
